pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    docker.build('frontend-image')
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    docker.image('frontend-image').run('-d -p 8080:80 --name frontend-container')
                }
            }
        }
    }
}
