pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    docker.build('backend-image')
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    docker.image('backend-image').run('-d -p 3000:3000 --name backend-container')
                }
            }
        }
    }
}
